[projects]

  # Default project, used when calling serve() or pdf().
  [projects.default]
  contents = [
      "main"
  ]

  # Output pdf or docx filename.
  output_filename = "Julia_Developers_Toolkit"

  # Port used by serve().
  port = 8011

  # Prefix for GitHub Pages links.
  online_url_prefix = "JuliaDevelopersToolkit/en"
