# The EN and ZH version can be served at the same time.

[projects]

  # Default project, used when calling serve() or pdf().
  [projects.en]
  homepage_contents = "index_en"

  metadata_path = "metadata_en.yml"


  contents = [
    "main_en"
  ]

  # Output pdf or docx filename.
  output_filename = "Julia_Developers_Toolkit_EN"

  # Port used by serve().
  port = 8011

  # Prefix for GitHub Pages links.
  online_url_prefix = "JuliaDevelopersToolkit/en"

  # Extra directories to copy into build each iteration of serve and when building site.
  extra_directories = [
    "resources"
  ]


  [projects.default]
  homepage_contents = "index_zh"

  metadata_path = "metadata_zh.yml"

  contents = [
    "prepare_environment_zh",
    "REPL_zh"
  ]

  # Output pdf or docx filename.
  output_filename = "Julia_Developers_Toolkit_ZH"

  # Port used by serve(project="zh").
  port = 8012

  # Prefix for GitHub Pages links.
  online_url_prefix = "JuliaDevelopersToolkit/zh"

  # Extra directories to copy into build each iteration of serve and when building site.
  extra_directories = [
    "resources"
  ]
