name = "JuliaDevelopersToolkit"
uuid = "87ae80f2-9a2a-4fe6-8e87-4661785be4b7"
authors = ["Jun Tian <tianjun.cpp@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
