[projects]

  # Default project, used when calling serve() or pdf().
  [projects.default]
  contents = [
      "main"
  ]

  # Output pdf or docx filename.
  output_filename = "Julia开发者的工具箱"

  # Port used by serve().
  port = 8010

  # Prefix for GitHub Pages links.
  online_url_prefix = "JuliaDevelopersToolkit/zh"
