name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test-and-deploy:
    name: Test and deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: julia-actions/setup-julia@v1
        with:
          version: '^1.6.0-0'

      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      - uses: julia-actions/julia-runtest@v1

      - name: Build books
        run: |
          cd books
          mkdir build
          cd en
          julia --project -e 'using Pkg; Pkg.instantiate(); include("build.jl")'
          mv build ../build
          cd ../zh
          julia --project -e 'using Pkg; Pkg.instantiate(); include("build.jl")'
          mv build ../build

      - name: Deploy to secondary branch
        if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: ./books/build/
